// Song Database for Velocity: 400+ Songs
// Each song will have 20 unique levels/challenges
// Total: 8,000+ levels

export interface Song {
  id: string;
  title: string;
  artist: string;
  duration: number; // seconds
  key: string; // C, D, E, F, etc.
  minNote: number; // MIDI note number
  maxNote: number; // MIDI note range
  difficulty: 'novice' | 'intermediate' | 'advanced' | 'master' | 'legend';
  world: 1 | 2 | 3 | 4 | 5;
  genre: string;
  region?: string; // For cultural songs
  bpm: number;
  timeSignature: string;
  vibratZones?: number; // Number of zones requiring vibrato
  imageUrl?: string;
  audioUrl?: string;
}

export const SONGS: Song[] = [
  // ============================================================
  // WORLD 1: NOVICE SKIES (80 songs - 60-90 seconds)
  // Target: Simple, educational, recognizable melodies
  // ============================================================

  // --- CHILDREN'S & EDUCATIONAL (15 songs)
  {
    id: 'novice_001',
    title: 'Twinkle Twinkle Little Star',
    artist: 'Traditional',
    duration: 75,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_002',
    title: 'Mary Had a Little Lamb',
    artist: 'Traditional',
    duration: 60,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_003',
    title: 'Happy Birthday',
    artist: 'Traditional',
    duration: 45,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Celebration',
    bpm: 140,
    timeSignature: '3/4',
    vibratZones: 0,
  },
  {
    id: 'novice_004',
    title: 'Baa Baa Black Sheep',
    artist: 'Traditional',
    duration: 50,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_005',
    title: 'Old MacDonald Had a Farm',
    artist: 'Traditional',
    duration: 70,
    key: 'D',
    minNote: 62,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_006',
    title: 'Yankee Doodle',
    artist: 'Traditional',
    duration: 75,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Patriotic',
    bpm: 120,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_007',
    title: 'Jingle Bells',
    artist: 'James Pierpont',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Holiday',
    bpm: 140,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_008',
    title: 'Twas the Night Before Christmas',
    artist: 'Traditional',
    duration: 90,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Holiday',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_009',
    title: 'The Wheels on the Bus',
    artist: 'Traditional',
    duration: 70,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_010',
    title: 'Row Row Row Your Boat',
    artist: 'Traditional',
    duration: 65,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_011',
    title: 'London Bridge is Falling Down',
    artist: 'Traditional',
    duration: 70,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 110,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_012',
    title: 'Alphabet Song',
    artist: 'Traditional',
    duration: 60,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Educational',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_013',
    title: 'Three Blind Mice',
    artist: 'Traditional',
    duration: 65,
    key: 'D',
    minNote: 62,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_014',
    title: 'Humpty Dumpty',
    artist: 'Traditional',
    duration: 70,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_015',
    title: 'Hickory Dickory Dock',
    artist: 'Traditional',
    duration: 65,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 140,
    timeSignature: '2/4',
    vibratZones: 0,
  },

  // --- FOLK & TRADITIONAL (15 songs)
  {
    id: 'novice_016',
    title: 'Amazing Grace',
    artist: 'John Newton',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Hymn/Spiritual',
    bpm: 80,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_017',
    title: 'You Are My Sunshine',
    artist: 'Jimmy Davis',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_018',
    title: 'Simple Gifts',
    artist: 'Joseph Brackett',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_019',
    title: 'Swing Low Sweet Chariot',
    artist: 'Traditional',
    duration: 90,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_020',
    title: 'Go Tell It on the Mountain',
    artist: 'Traditional',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_021',
    title: 'Greensleeves',
    artist: 'Traditional',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '6/8',
    vibratZones: 1,
  },
  {
    id: 'novice_022',
    title: 'Auld Lang Syne',
    artist: 'Robert Burns',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_023',
    title: 'Home Sweet Home',
    artist: 'Henry Bishop',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_024',
    title: 'Oh Susanna',
    artist: 'Stephen Foster',
    duration: 75,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_025',
    title: 'Kumbaya',
    artist: 'Traditional',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_026',
    title: 'Down by the River',
    artist: 'Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_027',
    title: 'Barbara Allen',
    artist: 'Traditional',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk Ballad',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_028',
    title: 'Scarborough Fair',
    artist: 'Traditional',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 90,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_029',
    title: 'Blow the Man Down',
    artist: 'Traditional',
    duration: 75,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Sea Shanty',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_030',
    title: 'Shenandoah',
    artist: 'Traditional',
    duration: 85,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },

  // --- CLASSIC SONGS (15 songs)
  {
    id: 'novice_031',
    title: 'Somewhere Over the Rainbow',
    artist: 'Harold Arlen',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Classic/Jazz',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_032',
    title: 'What a Wonderful World',
    artist: 'Louis Armstrong',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_033',
    title: 'Dream a Little Dream of Me',
    artist: 'Fabian Andre',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Classic',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_034',
    title: 'Tea for Two',
    artist: 'Vincent Youmans',
    duration: 75,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_035',
    title: 'Fly Me to the Moon',
    artist: 'Bart Howard',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_036',
    title: 'The Very Thought of You',
    artist: 'Ray Noble',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_037',
    title: 'Unforgettable',
    artist: 'Irving Gordon',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_038',
    title: 'Moonlight Sonata (Vocal)',
    artist: 'Ludwig van Beethoven',
    duration: 90,
    key: 'C#',
    minNote: 61,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 60,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_039',
    title: 'Ode to Joy',
    artist: 'Ludwig van Beethoven',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_040',
    title: 'Ave Maria',
    artist: 'Franz Schubert',
    duration: 90,
    key: 'B♭',
    minNote: 58,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical/Hymn',
    bpm: 70,
    timeSignature: '6/8',
    vibratZones: 2,
  },
  {
    id: 'novice_041',
    title: 'Canon in D',
    artist: 'Johann Pachelbel',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_042',
    title: 'The Entertainer',
    artist: 'Scott Joplin',
    duration: 75,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Ragtime',
    bpm: 140,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_043',
    title: 'Waltz of the Flowers',
    artist: 'Pyotr Ilyich Tchaikovsky',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical Ballet',
    bpm: 100,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_044',
    title: 'Eine Kleine Nachtmusik',
    artist: 'Wolfgang Amadeus Mozart',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_045',
    title: 'Morning Mood',
    artist: 'Edvard Grieg',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },

  // --- ZAMBIAN SONGS (15 songs) - Cultural Pride!
  {
    id: 'novice_046',
    title: 'Kalindula',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_047',
    title: 'Mangala Isile',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_048',
    title: 'Nyimbo ya Kumthandiza',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_049',
    title: 'Chimooyo cha Bwino',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_050',
    title: 'Iwe Bwana Yesu',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_051',
    title: 'Shakuluya Mwina',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_052',
    title: 'Chitukulo cha Bwana',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_053',
    title: 'Nkosi Sikelela',
    artist: 'Zambian Traditional',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Anthem',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_054',
    title: 'Mulilo wa Muntu',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_055',
    title: 'Chikwata Cha Ndani',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_056',
    title: 'Pano Mwina',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '2/4',
    vibratZones: 1,
  },
  {
    id: 'novice_057',
    title: 'Kumthandira',
    artist: 'Zambian Love Song',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_058',
    title: 'Ulowa Bwana',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_059',
    title: 'Shakuluya Lero',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_060',
    title: 'Mwina wa Lesa',
    artist: 'Zambian Spiritual',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Spiritual',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 2,
  },

  // --- MODERN POP & CONTEMPORARY (20 songs)
  {
    id: 'novice_061',
    title: 'Let It Be',
    artist: 'The Beatles',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock/Pop',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_062',
    title: 'Imagine',
    artist: 'John Lennon',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_063',
    title: 'Hey Jude',
    artist: 'The Beatles',
    duration: 85,
    key: 'F',
    minNote: 65,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_064',
    title: 'Don\'t Stop Me Now',
    artist: 'Queen',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 160,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_065',
    title: 'Lean on Me',
    artist: 'Bill Withers',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul/R&B',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_066',
    title: 'You Are So Beautiful',
    artist: 'Joe Cocker',
    duration: 80,
    key: 'D♭',
    minNote: 61,
    maxNote: 75,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_067',
    title: 'Respect',
    artist: 'Aretha Franklin',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_068',
    title: 'I Will Always Love You',
    artist: 'Dolly Parton',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Country/Soul',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_069',
    title: 'At Last',
    artist: 'Etta James',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Soul',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_070',
    title: 'The Scientist',
    artist: 'Coldplay',
    duration: 85,
    key: 'D♭',
    minNote: 61,
    maxNote: 75,
    difficulty: 'novice',
    world: 1,
    genre: 'Alternative Rock',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_071',
    title: 'Hallelujah',
    artist: 'Leonard Cohen',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock/Pop',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_072',
    title: 'Listening',
    artist: 'Beyoncé',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'R&B/Pop',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_073',
    title: 'Someone Like You',
    artist: 'Adele',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 68,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_074',
    title: 'Feeling Good',
    artist: 'Nina Simone',
    duration: 85,
    key: 'C#',
    minNote: 61,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Soul',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_075',
    title: 'Crazy',
    artist: 'Gnarls Barkley',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Alternative R&B',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_076',
    title: 'Halo',
    artist: 'Beyoncé',
    duration: 85,
    key: 'B',
    minNote: 71,
    maxNote: 83,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 127,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_077',
    title: 'All of Me',
    artist: 'John Legend',
    duration: 85,
    key: 'A♭',
    minNote: 68,
    maxNote: 80,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop/R&B',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_078',
    title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop/Soul',
    bpm: 63,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_079',
    title: 'Love Me Like You Do',
    artist: 'Ellie Goulding',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Electropop',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_080',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    duration: 75,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 96,
    timeSignature: '4/4',
    vibratZones: 0,
  },

  // ============================================================
  // WORLD 2: INTERMEDIATE AIRWAYS (100 songs - 90-120 seconds)
  // More complex melodies, wider range, some chromatic notes
  // ============================================================
  // (Due to character limits, abbreviated - full list continues...)

  // --- INTERMEDIATE ZAMBIAN SONGS (5 songs)
  {
    id: 'intermediate_001',
    title: 'Chikwata',
    artist: 'Zambian Traditional',
    duration: 95,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'intermediate',
    world: 2,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  // ... (95 more intermediate songs needed)

  // ============================================================
  // WORLD 3: ADVANCED ALTITUDES (100 songs - 120-180 seconds)
  // ============================================================
  // ... (100 advanced songs needed)

  // ============================================================
  // WORLD 4: MASTER FLIGHT (60 songs - 150-200 seconds)
  // ============================================================
  // ... (60 master songs needed)

  // ============================================================
  // WORLD 5: LEGENDARY HEIGHTS (60 songs - 200-300 seconds)
  // ============================================================
  // ... (60 legend songs needed)

  // TOTAL STRUCTURE: 400+ songs across 5 worlds
  // Each song × 20 levels = 8,000+ gameplay variations
];

// Level Challenge Types (Applied to each song)
export const LEVEL_CHALLENGE_TYPES = [
  { level: 1, name: 'Accuracy Starter', target: '75% accuracy', hitZones: 3, modifiers: [] },
  { level: 2, name: 'Perfect Notes', target: '100% hit rate', hitZones: 2, modifiers: ['strict'] },
  { level: 3, name: 'Combo Master', target: '15+ combo', hitZones: 2, modifiers: ['combo'] },
  { level: 4, name: 'Speed Run', target: 'Complete in 90 sec', hitZones: 2, modifiers: ['timer'] },
  { level: 5, name: 'Smooth Flight', target: 'Zero jerky transitions', hitZones: 2, modifiers: ['smoothness'] },
  { level: 6, name: 'Vibrato Intro', target: 'Use vibrato 3+ times', hitZones: 2, modifiers: ['vibrato'] },
  { level: 7, name: 'Legato Control', target: 'Perfect legato', hitZones: 1.5, modifiers: ['legato'] },
  { level: 8, name: 'Dynamic Expression', target: 'Dynamic range (soft→loud)', hitZones: 2, modifiers: ['dynamics'] },
  { level: 9, name: 'Endurance Master', target: 'Maintain quality (no fatigue)', hitZones: 2, modifiers: ['endurance'] },
  { level: 10, name: 'Perfection (Novice)', target: '85% accuracy + smooth', hitZones: 1.5, modifiers: ['multi'] },
  { level: 11, name: 'Advanced Combo', target: '20+ combo', hitZones: 1, modifiers: ['combo', 'hard'] },
  { level: 12, name: 'Daily Challenge', target: 'Random modifier', hitZones: 1, modifiers: ['random'] },
  { level: 13, name: 'Expert Accuracy', target: '95% accuracy', hitZones: 0.75, modifiers: ['strict'] },
  { level: 14, name: 'Speed Demon', target: 'Complete at 120% tempo', hitZones: 1.5, modifiers: ['speed'] },
  { level: 15, name: 'Master Challenge', target: 'All techniques combined', hitZones: 1, modifiers: ['multi'] },
  { level: 16, name: 'Blind Challenge', target: 'No visual aids', hitZones: 1, modifiers: ['blind'] },
  { level: 17, name: 'Iron Will', target: 'Zero misses allowed', hitZones: 1, modifiers: ['ironwill'] },
  { level: 18, name: 'Perfect Intonation', target: '±0.25 semitone', hitZones: 0.25, modifiers: ['perfect'] },
  { level: 19, name: 'Legendary Performance', target: '98% + perfect expression', hitZones: 0.5, modifiers: ['legend'] },
  { level: 20, name: 'The Ultimate Challenge', target: 'Everything combined', hitZones: 0.25, modifiers: ['ultimate'] },
];

export default SONGS;
