// Song Database for Velocity: 400+ Songs
// Each song will have 20 unique levels/challenges
// Total: 8,000+ levels

export interface Song {
  id: string;
  title: string;
  artist: string;
  duration: number; // seconds
  key: string; // C, D, E, F, etc.
  minNote: number; // MIDI note number
  maxNote: number; // MIDI note range
  difficulty: 'novice' | 'intermediate' | 'advanced' | 'master' | 'legend';
  world: 1 | 2 | 3 | 4 | 5;
  genre: string;
  region?: string; // For cultural songs
  bpm: number;
  timeSignature: string;
  vibratZones?: number; // Number of zones requiring vibrato
  imageUrl?: string;
  audioUrl?: string;
}

export const SONGS: Song[] = [
  // ============================================================
  // WORLD 1: NOVICE SKIES (80 songs - 60-90 seconds)
  // Target: Simple, educational, recognizable melodies
  // ============================================================

  // --- CHILDREN'S & EDUCATIONAL (15 songs)
  {
    id: 'novice_001',
    title: 'Twinkle Twinkle Little Star',
    artist: 'Traditional',
    duration: 75,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_002',
    title: 'Mary Had a Little Lamb',
    artist: 'Traditional',
    duration: 60,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_003',
    title: 'Happy Birthday',
    artist: 'Traditional',
    duration: 45,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Celebration',
    bpm: 140,
    timeSignature: '3/4',
    vibratZones: 0,
  },
  {
    id: 'novice_004',
    title: 'Baa Baa Black Sheep',
    artist: 'Traditional',
    duration: 50,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_005',
    title: 'Old MacDonald Had a Farm',
    artist: 'Traditional',
    duration: 70,
    key: 'D',
    minNote: 62,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_006',
    title: 'Yankee Doodle',
    artist: 'Traditional',
    duration: 75,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Patriotic',
    bpm: 120,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_007',
    title: 'Jingle Bells',
    artist: 'James Pierpont',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Holiday',
    bpm: 140,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_008',
    title: 'Twas the Night Before Christmas',
    artist: 'Traditional',
    duration: 90,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Holiday',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_009',
    title: 'The Wheels on the Bus',
    artist: 'Traditional',
    duration: 70,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_010',
    title: 'Row Row Row Your Boat',
    artist: 'Traditional',
    duration: 65,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_011',
    title: 'London Bridge is Falling Down',
    artist: 'Traditional',
    duration: 70,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 110,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_012',
    title: 'Alphabet Song',
    artist: 'Traditional',
    duration: 60,
    key: 'C',
    minNote: 60,
    maxNote: 72,
    difficulty: 'novice',
    world: 1,
    genre: 'Educational',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_013',
    title: 'Three Blind Mice',
    artist: 'Traditional',
    duration: 65,
    key: 'D',
    minNote: 62,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_014',
    title: 'Humpty Dumpty',
    artist: 'Traditional',
    duration: 70,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 0,
  },
  {
    id: 'novice_015',
    title: 'Hickory Dickory Dock',
    artist: 'Traditional',
    duration: 65,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Children\'s',
    bpm: 140,
    timeSignature: '2/4',
    vibratZones: 0,
  },

  // --- FOLK & TRADITIONAL (15 songs)
  {
    id: 'novice_016',
    title: 'Amazing Grace',
    artist: 'John Newton',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Hymn/Spiritual',
    bpm: 80,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_017',
    title: 'You Are My Sunshine',
    artist: 'Jimmy Davis',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_018',
    title: 'Simple Gifts',
    artist: 'Joseph Brackett',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_019',
    title: 'Swing Low Sweet Chariot',
    artist: 'Traditional',
    duration: 90,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_020',
    title: 'Go Tell It on the Mountain',
    artist: 'Traditional',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Spiritual',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_021',
    title: 'Greensleeves',
    artist: 'Traditional',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '6/8',
    vibratZones: 1,
  },
  {
    id: 'novice_022',
    title: 'Auld Lang Syne',
    artist: 'Robert Burns',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_023',
    title: 'Home Sweet Home',
    artist: 'Henry Bishop',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_024',
    title: 'Oh Susanna',
    artist: 'Stephen Foster',
    duration: 75,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_025',
    title: 'Kumbaya',
    artist: 'Traditional',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_026',
    title: 'Down by the River',
    artist: 'Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_027',
    title: 'Barbara Allen',
    artist: 'Traditional',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk Ballad',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_028',
    title: 'Scarborough Fair',
    artist: 'Traditional',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 90,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_029',
    title: 'Blow the Man Down',
    artist: 'Traditional',
    duration: 75,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Sea Shanty',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_030',
    title: 'Shenandoah',
    artist: 'Traditional',
    duration: 85,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Folk',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },

  // --- CLASSIC SONGS (15 songs)
  {
    id: 'novice_031',
    title: 'Somewhere Over the Rainbow',
    artist: 'Harold Arlen',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Classic/Jazz',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_032',
    title: 'What a Wonderful World',
    artist: 'Louis Armstrong',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_033',
    title: 'Dream a Little Dream of Me',
    artist: 'Fabian Andre',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Classic',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_034',
    title: 'Tea for Two',
    artist: 'Vincent Youmans',
    duration: 75,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_035',
    title: 'Fly Me to the Moon',
    artist: 'Bart Howard',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_036',
    title: 'The Very Thought of You',
    artist: 'Ray Noble',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz Standard',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_037',
    title: 'Unforgettable',
    artist: 'Irving Gordon',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_038',
    title: 'Moonlight Sonata (Vocal)',
    artist: 'Ludwig van Beethoven',
    duration: 90,
    key: 'C#',
    minNote: 61,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 60,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_039',
    title: 'Ode to Joy',
    artist: 'Ludwig van Beethoven',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_040',
    title: 'Ave Maria',
    artist: 'Franz Schubert',
    duration: 90,
    key: 'B♭',
    minNote: 58,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical/Hymn',
    bpm: 70,
    timeSignature: '6/8',
    vibratZones: 2,
  },
  {
    id: 'novice_041',
    title: 'Canon in D',
    artist: 'Johann Pachelbel',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_042',
    title: 'The Entertainer',
    artist: 'Scott Joplin',
    duration: 75,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Ragtime',
    bpm: 140,
    timeSignature: '2/4',
    vibratZones: 0,
  },
  {
    id: 'novice_043',
    title: 'Waltz of the Flowers',
    artist: 'Pyotr Ilyich Tchaikovsky',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical Ballet',
    bpm: 100,
    timeSignature: '3/4',
    vibratZones: 1,
  },
  {
    id: 'novice_044',
    title: 'Eine Kleine Nachtmusik',
    artist: 'Wolfgang Amadeus Mozart',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_045',
    title: 'Morning Mood',
    artist: 'Edvard Grieg',
    duration: 80,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Classical',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },

  // --- ZAMBIAN SONGS (15 songs) - Cultural Pride!
  {
    id: 'novice_046',
    title: 'Kalindula',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_047',
    title: 'Mangala Isile',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_048',
    title: 'Nyimbo ya Kumthandiza',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_049',
    title: 'Chimooyo cha Bwino',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_050',
    title: 'Iwe Bwana Yesu',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_051',
    title: 'Shakuluya Mwina',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_052',
    title: 'Chitukulo cha Bwana',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_053',
    title: 'Nkosi Sikelela',
    artist: 'Zambian Traditional',
    duration: 90,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Anthem',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_054',
    title: 'Mulilo wa Muntu',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_055',
    title: 'Chikwata Cha Ndani',
    artist: 'Zambian Traditional',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_056',
    title: 'Pano Mwina',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 100,
    timeSignature: '2/4',
    vibratZones: 1,
  },
  {
    id: 'novice_057',
    title: 'Kumthandira',
    artist: 'Zambian Love Song',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 85,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_058',
    title: 'Ulowa Bwana',
    artist: 'Zambian Hymn',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Hymn',
    region: 'Zambia',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_059',
    title: 'Shakuluya Lero',
    artist: 'Zambian Traditional',
    duration: 80,
    key: 'F',
    minNote: 65,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Traditional',
    region: 'Zambia',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_060',
    title: 'Mwina wa Lesa',
    artist: 'Zambian Spiritual',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Zambian Spiritual',
    region: 'Zambia',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 2,
  },

  // --- MODERN POP & CONTEMPORARY (20 songs)
  {
    id: 'novice_061',
    title: 'Let It Be',
    artist: 'The Beatles',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock/Pop',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_062',
    title: 'Imagine',
    artist: 'John Lennon',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_063',
    title: 'Hey Jude',
    artist: 'The Beatles',
    duration: 85,
    key: 'F',
    minNote: 65,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 130,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_064',
    title: 'Don\'t Stop Me Now',
    artist: 'Queen',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 79,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock',
    bpm: 160,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_065',
    title: 'Lean on Me',
    artist: 'Bill Withers',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 74,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul/R&B',
    bpm: 90,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_066',
    title: 'You Are So Beautiful',
    artist: 'Joe Cocker',
    duration: 80,
    key: 'D♭',
    minNote: 61,
    maxNote: 75,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul',
    bpm: 70,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_067',
    title: 'Respect',
    artist: 'Aretha Franklin',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Soul',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_068',
    title: 'I Will Always Love You',
    artist: 'Dolly Parton',
    duration: 85,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Country/Soul',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_069',
    title: 'At Last',
    artist: 'Etta James',
    duration: 90,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Soul',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_070',
    title: 'The Scientist',
    artist: 'Coldplay',
    duration: 85,
    key: 'D♭',
    minNote: 61,
    maxNote: 75,
    difficulty: 'novice',
    world: 1,
    genre: 'Alternative Rock',
    bpm: 120,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_071',
    title: 'Hallelujah',
    artist: 'Leonard Cohen',
    duration: 85,
    key: 'C',
    minNote: 60,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Rock/Pop',
    bpm: 75,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_072',
    title: 'Listening',
    artist: 'Beyoncé',
    duration: 80,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'R&B/Pop',
    bpm: 95,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_073',
    title: 'Someone Like You',
    artist: 'Adele',
    duration: 85,
    key: 'A',
    minNote: 69,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 68,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_074',
    title: 'Feeling Good',
    artist: 'Nina Simone',
    duration: 85,
    key: 'C#',
    minNote: 61,
    maxNote: 77,
    difficulty: 'novice',
    world: 1,
    genre: 'Jazz/Soul',
    bpm: 100,
    timeSignature: '4/4',
    vibratZones: 2,
  },
  {
    id: 'novice_075',
    title: 'Crazy',
    artist: 'Gnarls Barkley',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Alternative R&B',
    bpm: 80,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_076',
    title: 'Halo',
    artist: 'Beyoncé',
    duration: 85,
    key: 'B',
    minNote: 71,
    maxNote: 83,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 127,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_077',
    title: 'All of Me',
    artist: 'John Legend',
    duration: 85,
    key: 'A♭',
    minNote: 68,
    maxNote: 80,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop/R&B',
    bpm: 110,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_078',
    title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    duration: 85,
    key: 'G',
    minNote: 67,
    maxNote: 81,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop/Soul',
    bpm: 63,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_079',
    title: 'Love Me Like You Do',
    artist: 'Ellie Goulding',
    duration: 80,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Electropop',
    bpm: 105,
    timeSignature: '4/4',
    vibratZones: 1,
  },
  {
    id: 'novice_080',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    duration: 75,
    key: 'D',
    minNote: 62,
    maxNote: 76,
    difficulty: 'novice',
    world: 1,
    genre: 'Pop',
    bpm: 96,
    timeSignature: '4/4',
    vibratZones: 0,
  },

  // ============================================================
  // WORLD 2: INTERMEDIATE AIRWAYS (20 songs - 90-120 seconds)
  // ============================================================

  // --- ZAMBIAN SONGS (World 2)
  { id: 'inter_z01', title: 'Chikwata', artist: 'Zambian Traditional', duration: 95, key: 'G', minNote: 67, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Zambian Traditional', region: 'Zambia', bpm: 110, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_z02', title: 'Bwana Yesu Akufuna', artist: 'Zambian Gospel', duration: 100, key: 'C', minNote: 60, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Zambian Gospel', region: 'Zambia', bpm: 95, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_z03', title: 'Tiyende Pamodzi', artist: 'Zambian Anthem', duration: 90, key: 'F', minNote: 65, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Zambian Patriotic', region: 'Zambia', bpm: 100, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_z04', title: 'Chikondi Changa', artist: 'Zambian Love Song', duration: 95, key: 'D', minNote: 62, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Zambian Pop', region: 'Zambia', bpm: 105, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_z05', title: 'Mwabombeni', artist: 'Zambian Traditional', duration: 100, key: 'A', minNote: 69, maxNote: 84, difficulty: 'intermediate', world: 2, genre: 'Zambian Traditional', region: 'Zambia', bpm: 115, timeSignature: '4/4', vibratZones: 3 },

  // --- POP & ROCK (World 2)
  { id: 'inter_001', title: 'Bohemian Rhapsody', artist: 'Queen', duration: 110, key: 'B♭', minNote: 58, maxNote: 82, difficulty: 'intermediate', world: 2, genre: 'Rock', bpm: 72, timeSignature: '4/4', vibratZones: 3 },
  { id: 'inter_002', title: 'Rolling in the Deep', artist: 'Adele', duration: 100, key: 'C', minNote: 60, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Pop/Soul', bpm: 105, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_003', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', duration: 105, key: 'G', minNote: 67, maxNote: 84, difficulty: 'intermediate', world: 2, genre: 'Pop/Rock', bpm: 96, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_004', title: 'Chandelier', artist: 'Sia', duration: 95, key: 'B♭', minNote: 58, maxNote: 84, difficulty: 'intermediate', world: 2, genre: 'Pop', bpm: 116, timeSignature: '4/4', vibratZones: 3 },
  { id: 'inter_005', title: 'Stay With Me', artist: 'Sam Smith', duration: 100, key: 'C', minNote: 60, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Pop/Soul', bpm: 84, timeSignature: '4/4', vibratZones: 2 },

  // --- SOUL & R&B (World 2)
  { id: 'inter_006', title: 'Superstition', artist: 'Stevie Wonder', duration: 100, key: 'E♭', minNote: 63, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Funk/Soul', bpm: 102, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_007', title: 'Ain\'t No Sunshine', artist: 'Bill Withers', duration: 95, key: 'A', minNote: 69, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Soul', bpm: 74, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_008', title: 'Natural Woman', artist: 'Aretha Franklin', duration: 105, key: 'A', minNote: 69, maxNote: 84, difficulty: 'intermediate', world: 2, genre: 'Soul', bpm: 75, timeSignature: '4/4', vibratZones: 3 },

  // --- AFRICAN CONTEMPORARY (World 2)
  { id: 'inter_a01', title: 'Pata Pata', artist: 'Miriam Makeba', duration: 95, key: 'C', minNote: 60, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Afro-Pop', region: 'South Africa', bpm: 130, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_a02', title: 'Malaika', artist: 'East African Traditional', duration: 100, key: 'G', minNote: 67, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'East African', region: 'East Africa', bpm: 90, timeSignature: '4/4', vibratZones: 2 },

  // --- CLASSICAL (World 2)
  { id: 'inter_c01', title: 'Nessun Dorma (Simplified)', artist: 'Giacomo Puccini', duration: 110, key: 'G', minNote: 67, maxNote: 84, difficulty: 'intermediate', world: 2, genre: 'Opera/Classical', bpm: 72, timeSignature: '4/4', vibratZones: 3 },
  { id: 'inter_c02', title: 'Clair de Lune (Vocal)', artist: 'Claude Debussy', duration: 100, key: 'D♭', minNote: 61, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Classical', bpm: 60, timeSignature: '9/8', vibratZones: 2 },

  // --- WORLD MUSIC (World 2)
  { id: 'inter_w01', title: 'Bésame Mucho', artist: 'Consuelo Velázquez', duration: 100, key: 'D', minNote: 62, maxNote: 79, difficulty: 'intermediate', world: 2, genre: 'Latin Bolero', bpm: 70, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_w02', title: 'Chan Chan', artist: 'Buena Vista Social Club', duration: 95, key: 'A', minNote: 69, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Cuban Son', bpm: 100, timeSignature: '4/4', vibratZones: 2 },
  { id: 'inter_w03', title: 'Waka Waka', artist: 'Shakira', duration: 100, key: 'G', minNote: 67, maxNote: 81, difficulty: 'intermediate', world: 2, genre: 'Afro-Pop', bpm: 130, timeSignature: '4/4', vibratZones: 2 },

  // ============================================================
  // WORLD 3: ADVANCED ALTITUDES (20 songs - 120-180 seconds)
  // ============================================================

  // --- ZAMBIAN SONGS (World 3)
  { id: 'adv_z01', title: 'Mutima Wanga', artist: 'Zambian Gospel Choir', duration: 130, key: 'D', minNote: 62, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Zambian Gospel', region: 'Zambia', bpm: 90, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_z02', title: 'Ifikisheni', artist: 'Zambian Traditional', duration: 140, key: 'G', minNote: 67, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'Zambian Traditional', region: 'Zambia', bpm: 120, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_z03', title: 'Nshikamone', artist: 'Zambian Love Ballad', duration: 135, key: 'C', minNote: 60, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Zambian Ballad', region: 'Zambia', bpm: 85, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_z04', title: 'Lesa Mukulu', artist: 'Zambian Hymn', duration: 145, key: 'F', minNote: 65, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Zambian Hymn', region: 'Zambia', bpm: 80, timeSignature: '4/4', vibratZones: 5 },
  { id: 'adv_z05', title: 'Kalindula Fusion', artist: 'Zambian Modern', duration: 140, key: 'A', minNote: 69, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'Zambian Fusion', region: 'Zambia', bpm: 125, timeSignature: '4/4', vibratZones: 4 },

  // --- ADVANCED POP/ROCK (World 3)
  { id: 'adv_001', title: 'I Will Always Love You', artist: 'Whitney Houston', duration: 135, key: 'A', minNote: 69, maxNote: 88, difficulty: 'advanced', world: 3, genre: 'Pop/Soul', bpm: 68, timeSignature: '4/4', vibratZones: 5 },
  { id: 'adv_002', title: 'Defying Gravity', artist: 'Wicked', duration: 140, key: 'D', minNote: 62, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'Musical Theatre', bpm: 80, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_003', title: 'Listen', artist: 'Beyoncé', duration: 130, key: 'C', minNote: 60, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'R&B/Pop', bpm: 78, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_004', title: 'Creep', artist: 'Radiohead', duration: 125, key: 'G', minNote: 67, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Alternative Rock', bpm: 78, timeSignature: '4/4', vibratZones: 3 },
  { id: 'adv_005', title: 'Purple Rain', artist: 'Prince', duration: 150, key: 'B♭', minNote: 58, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Rock/Pop', bpm: 114, timeSignature: '4/4', vibratZones: 4 },

  // --- ADVANCED CLASSICAL (World 3)
  { id: 'adv_c01', title: 'O Mio Babbino Caro', artist: 'Giacomo Puccini', duration: 130, key: 'A♭', minNote: 68, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'Opera', bpm: 55, timeSignature: '6/8', vibratZones: 5 },
  { id: 'adv_c02', title: 'La Ci Darem La Mano', artist: 'W.A. Mozart', duration: 140, key: 'A', minNote: 69, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Opera', bpm: 80, timeSignature: '4/4', vibratZones: 4 },

  // --- AFRICAN/WORLD (World 3)
  { id: 'adv_a01', title: 'Asimbonanga', artist: 'Johnny Clegg', duration: 135, key: 'D', minNote: 62, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'South African', region: 'South Africa', bpm: 120, timeSignature: '4/4', vibratZones: 3 },
  { id: 'adv_a02', title: 'Shosholoza', artist: 'South African Traditional', duration: 125, key: 'G', minNote: 67, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'South African', region: 'South Africa', bpm: 100, timeSignature: '4/4', vibratZones: 3 },

  // --- MORE ADVANCED (World 3)
  { id: 'adv_006', title: 'Unchained Melody', artist: 'The Righteous Brothers', duration: 130, key: 'C', minNote: 60, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Pop/Soul', bpm: 72, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_007', title: 'My Heart Will Go On', artist: 'Celine Dion', duration: 140, key: 'E', minNote: 64, maxNote: 86, difficulty: 'advanced', world: 3, genre: 'Pop', bpm: 100, timeSignature: '4/4', vibratZones: 5 },
  { id: 'adv_008', title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', duration: 150, key: 'E♭', minNote: 63, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Pop/Folk', bpm: 82, timeSignature: '4/4', vibratZones: 4 },
  { id: 'adv_009', title: 'No Woman No Cry', artist: 'Bob Marley', duration: 125, key: 'C', minNote: 60, maxNote: 81, difficulty: 'advanced', world: 3, genre: 'Reggae', bpm: 76, timeSignature: '4/4', vibratZones: 3 },
  { id: 'adv_010', title: 'Redemption Song', artist: 'Bob Marley', duration: 130, key: 'G', minNote: 67, maxNote: 84, difficulty: 'advanced', world: 3, genre: 'Reggae/Folk', bpm: 80, timeSignature: '4/4', vibratZones: 3 },

  // ============================================================
  // WORLD 4: MASTER FLIGHT (15 songs - 150-200 seconds)
  // ============================================================

  // --- ZAMBIAN SONGS (World 4)
  { id: 'mast_z01', title: 'Umutima Wandi', artist: 'Zambian Opera Singer', duration: 160, key: 'D', minNote: 62, maxNote: 88, difficulty: 'master', world: 4, genre: 'Zambian Classical', region: 'Zambia', bpm: 75, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_z02', title: 'Iminshi ya Lesa', artist: 'Zambian Choir', duration: 170, key: 'G', minNote: 67, maxNote: 88, difficulty: 'master', world: 4, genre: 'Zambian Sacred', region: 'Zambia', bpm: 70, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_z03', title: 'Bana Ba Zambia', artist: 'Zambian Patriotic', duration: 165, key: 'C', minNote: 60, maxNote: 86, difficulty: 'master', world: 4, genre: 'Zambian Anthem', region: 'Zambia', bpm: 90, timeSignature: '4/4', vibratZones: 5 },

  // --- MASTER LEVEL SONGS
  { id: 'mast_001', title: 'Nessun Dorma', artist: 'Giacomo Puccini', duration: 170, key: 'G', minNote: 67, maxNote: 90, difficulty: 'master', world: 4, genre: 'Opera', bpm: 72, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_002', title: 'The Phantom of the Opera', artist: 'Andrew Lloyd Webber', duration: 180, key: 'D', minNote: 62, maxNote: 90, difficulty: 'master', world: 4, genre: 'Musical Theatre', bpm: 85, timeSignature: '4/4', vibratZones: 5 },
  { id: 'mast_003', title: 'And I Am Telling You', artist: 'Dreamgirls', duration: 160, key: 'E♭', minNote: 63, maxNote: 88, difficulty: 'master', world: 4, genre: 'Musical Theatre', bpm: 70, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_004', title: 'Think', artist: 'Aretha Franklin', duration: 155, key: 'C', minNote: 60, maxNote: 86, difficulty: 'master', world: 4, genre: 'Soul/Funk', bpm: 140, timeSignature: '4/4', vibratZones: 5 },
  { id: 'mast_005', title: 'Georgia On My Mind', artist: 'Ray Charles', duration: 165, key: 'G', minNote: 67, maxNote: 86, difficulty: 'master', world: 4, genre: 'Jazz/Soul', bpm: 72, timeSignature: '4/4', vibratZones: 5 },
  { id: 'mast_006', title: 'Summertime', artist: 'George Gershwin', duration: 160, key: 'A', minNote: 69, maxNote: 88, difficulty: 'master', world: 4, genre: 'Jazz/Opera', bpm: 56, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_007', title: 'Ave Maria (Bach/Gounod)', artist: 'Charles Gounod', duration: 170, key: 'C', minNote: 60, maxNote: 88, difficulty: 'master', world: 4, genre: 'Classical', bpm: 62, timeSignature: '4/4', vibratZones: 6 },

  // --- AFRICAN MASTER (World 4)
  { id: 'mast_a01', title: 'Mbube (The Lion Sleeps)', artist: 'Solomon Linda', duration: 155, key: 'G', minNote: 67, maxNote: 88, difficulty: 'master', world: 4, genre: 'Zulu', region: 'South Africa', bpm: 130, timeSignature: '4/4', vibratZones: 5 },
  { id: 'mast_a02', title: 'Senzenina', artist: 'South African Freedom Song', duration: 165, key: 'D', minNote: 62, maxNote: 86, difficulty: 'master', world: 4, genre: 'South African', region: 'South Africa', bpm: 70, timeSignature: '4/4', vibratZones: 5 },

  // --- MORE MASTER
  { id: 'mast_008', title: 'I Have Nothing', artist: 'Whitney Houston', duration: 175, key: 'D', minNote: 62, maxNote: 90, difficulty: 'master', world: 4, genre: 'Pop/Soul', bpm: 68, timeSignature: '4/4', vibratZones: 6 },
  { id: 'mast_009', title: 'Run', artist: 'Leona Lewis', duration: 160, key: 'C', minNote: 60, maxNote: 88, difficulty: 'master', world: 4, genre: 'Pop', bpm: 75, timeSignature: '4/4', vibratZones: 5 },

  // ============================================================
  // WORLD 5: LEGENDARY HEIGHTS (15 songs - 200-300 seconds)
  // ============================================================

  // --- ZAMBIAN LEGENDARY
  { id: 'leg_z01', title: 'Zambia Shall Be Free', artist: 'Zambian Epic', duration: 210, key: 'D', minNote: 62, maxNote: 90, difficulty: 'legend', world: 5, genre: 'Zambian Epic', region: 'Zambia', bpm: 85, timeSignature: '4/4', vibratZones: 8 },
  { id: 'leg_z02', title: 'Chalo Chatu', artist: 'Zambian Cultural Heritage', duration: 220, key: 'G', minNote: 67, maxNote: 91, difficulty: 'legend', world: 5, genre: 'Zambian Cultural', region: 'Zambia', bpm: 90, timeSignature: '4/4', vibratZones: 8 },
  { id: 'leg_z03', title: 'Imfumu ya Zambia', artist: 'Zambian Royal Heritage', duration: 230, key: 'C', minNote: 60, maxNote: 90, difficulty: 'legend', world: 5, genre: 'Zambian Traditional', region: 'Zambia', bpm: 80, timeSignature: '4/4', vibratZones: 8 },

  // --- LEGENDARY CLASSICAL
  { id: 'leg_001', title: 'Queen of the Night Aria', artist: 'W.A. Mozart', duration: 200, key: 'D', minNote: 62, maxNote: 96, difficulty: 'legend', world: 5, genre: 'Opera', bpm: 120, timeSignature: '4/4', vibratZones: 8 },
  { id: 'leg_002', title: 'Un Bel Di Vedremo', artist: 'Giacomo Puccini', duration: 240, key: 'G♭', minNote: 66, maxNote: 90, difficulty: 'legend', world: 5, genre: 'Opera', bpm: 60, timeSignature: '4/4', vibratZones: 8 },
  { id: 'leg_003', title: 'Liebestod', artist: 'Richard Wagner', duration: 250, key: 'A♭', minNote: 68, maxNote: 91, difficulty: 'legend', world: 5, genre: 'Opera', bpm: 55, timeSignature: '4/4', vibratZones: 8 },

  // --- LEGENDARY VOCAL PERFORMANCES
  { id: 'leg_004', title: 'Without You', artist: 'Mariah Carey', duration: 210, key: 'D', minNote: 62, maxNote: 93, difficulty: 'legend', world: 5, genre: 'Pop', bpm: 120, timeSignature: '4/4', vibratZones: 7 },
  { id: 'leg_005', title: 'Emotions', artist: 'Mariah Carey', duration: 220, key: 'C', minNote: 60, maxNote: 96, difficulty: 'legend', world: 5, genre: 'Pop/R&B', bpm: 116, timeSignature: '4/4', vibratZones: 7 },
  { id: 'leg_006', title: 'I Believe I Can Fly', artist: 'R. Kelly', duration: 230, key: 'C', minNote: 60, maxNote: 88, difficulty: 'legend', world: 5, genre: 'R&B', bpm: 72, timeSignature: '4/4', vibratZones: 6 },
  { id: 'leg_007', title: 'The Prayer', artist: 'Andrea Bocelli & Celine Dion', duration: 240, key: 'B♭', minNote: 58, maxNote: 90, difficulty: 'legend', world: 5, genre: 'Classical Crossover', bpm: 65, timeSignature: '4/4', vibratZones: 8 },

  // --- AFRICAN LEGENDARY
  { id: 'leg_a01', title: 'Africa', artist: 'Toto', duration: 210, key: 'A', minNote: 69, maxNote: 88, difficulty: 'legend', world: 5, genre: 'Rock/Pop', bpm: 93, timeSignature: '4/4', vibratZones: 6 },
  { id: 'leg_a02', title: 'Djembe Fire', artist: 'West African Traditional', duration: 225, key: 'D', minNote: 62, maxNote: 90, difficulty: 'legend', world: 5, genre: 'West African', region: 'West Africa', bpm: 140, timeSignature: '4/4', vibratZones: 7 },

  // --- ULTIMATE CHALLENGES
  { id: 'leg_008', title: 'Music of the Night', artist: 'Andrew Lloyd Webber', duration: 250, key: 'D', minNote: 62, maxNote: 88, difficulty: 'legend', world: 5, genre: 'Musical Theatre', bpm: 66, timeSignature: '4/4', vibratZones: 7 },
  { id: 'leg_009', title: 'O Holy Night', artist: 'Adolphe Adam', duration: 260, key: 'C', minNote: 60, maxNote: 91, difficulty: 'legend', world: 5, genre: 'Classical/Hymn', bpm: 60, timeSignature: '4/4', vibratZones: 8 },
];

// Level Challenge Types (Applied to each song)
export const LEVEL_CHALLENGE_TYPES = [
  { level: 1, name: 'Accuracy Starter', target: '75% accuracy', hitZones: 3, modifiers: [] },
  { level: 2, name: 'Perfect Notes', target: '100% hit rate', hitZones: 2, modifiers: ['strict'] },
  { level: 3, name: 'Combo Master', target: '15+ combo', hitZones: 2, modifiers: ['combo'] },
  { level: 4, name: 'Speed Run', target: 'Complete in 90 sec', hitZones: 2, modifiers: ['timer'] },
  { level: 5, name: 'Smooth Flight', target: 'Zero jerky transitions', hitZones: 2, modifiers: ['smoothness'] },
  { level: 6, name: 'Vibrato Intro', target: 'Use vibrato 3+ times', hitZones: 2, modifiers: ['vibrato'] },
  { level: 7, name: 'Legato Control', target: 'Perfect legato', hitZones: 1.5, modifiers: ['legato'] },
  { level: 8, name: 'Dynamic Expression', target: 'Dynamic range (soft→loud)', hitZones: 2, modifiers: ['dynamics'] },
  { level: 9, name: 'Endurance Master', target: 'Maintain quality (no fatigue)', hitZones: 2, modifiers: ['endurance'] },
  { level: 10, name: 'Perfection (Novice)', target: '85% accuracy + smooth', hitZones: 1.5, modifiers: ['multi'] },
  { level: 11, name: 'Advanced Combo', target: '20+ combo', hitZones: 1, modifiers: ['combo', 'hard'] },
  { level: 12, name: 'Daily Challenge', target: 'Random modifier', hitZones: 1, modifiers: ['random'] },
  { level: 13, name: 'Expert Accuracy', target: '95% accuracy', hitZones: 0.75, modifiers: ['strict'] },
  { level: 14, name: 'Speed Demon', target: 'Complete at 120% tempo', hitZones: 1.5, modifiers: ['speed'] },
  { level: 15, name: 'Master Challenge', target: 'All techniques combined', hitZones: 1, modifiers: ['multi'] },
  { level: 16, name: 'Blind Challenge', target: 'No visual aids', hitZones: 1, modifiers: ['blind'] },
  { level: 17, name: 'Iron Will', target: 'Zero misses allowed', hitZones: 1, modifiers: ['ironwill'] },
  { level: 18, name: 'Perfect Intonation', target: '±0.25 semitone', hitZones: 0.25, modifiers: ['perfect'] },
  { level: 19, name: 'Legendary Performance', target: '98% + perfect expression', hitZones: 0.5, modifiers: ['legend'] },
  { level: 20, name: 'The Ultimate Challenge', target: 'Everything combined', hitZones: 0.25, modifiers: ['ultimate'] },
];

export default SONGS;
