export const GameEvents = {
    GATE_PASSED: 'GATE_PASSED',
    CRASH: 'CRASH',
    UI_CLICK: 'UI_CLICK',
    LEVEL_START: 'LEVEL_START',
    LEVEL_COMPLETE: 'LEVEL_COMPLETE',
    OBSTACLE_DODGED: 'OBSTACLE_DODGED',
    QUEST_PROGRESS: 'QUEST_PROGRESS',
    QUEST_COMPLETED: 'QUEST_COMPLETED',
    VS_AI_PLAYER_WON: 'VS_AI_PLAYER_WON',
    RUN_RETURN_MENU: 'RUN_RETURN_MENU',
} as const;

export type GameEvent = typeof GameEvents[keyof typeof GameEvents];
