export const GameEvents = {
    GATE_PASSED: 'GATE_PASSED',
    COLLECTIBLE_PICKUP: 'COLLECTIBLE_PICKUP',
    CRASH: 'CRASH',
    UI_CLICK: 'UI_CLICK',
    LEVEL_START: 'LEVEL_START',
    LEVEL_COMPLETE: 'LEVEL_COMPLETE',
    LEVEL_FAILED: 'LEVEL_FAILED',
    LEVEL_SELECT: 'LEVEL_SELECT',
    ZONE_UNLOCKED: 'ZONE_UNLOCKED',
    OBSTACLE_DODGED: 'OBSTACLE_DODGED',
    DISTANCE_DELTA: 'DISTANCE_DELTA',
    QUEST_PROGRESS: 'QUEST_PROGRESS',
    QUEST_COMPLETED: 'QUEST_COMPLETED',
    LEARNING_HINT: 'LEARNING_HINT',
    STARS_AWARDED: 'STARS_AWARDED',
} as const;

export type GameEvent = typeof GameEvents[keyof typeof GameEvents];
